package modelo;
// Generated 16 dic 2021 19:50:39 by Hibernate Tools 5.5.7.Final

/**
 * Datos generated by hbm2java
 */
public class Datos implements java.io.Serializable {

	private DatosId id;
	private Estaciones estaciones;
	private String precipitaciones;
	private int temperaturaC;
	private int velocidadViento;

	public Datos() {
	}

	public Datos(DatosId id, Estaciones estaciones, String precipitaciones, int temperaturaC, int velocidadViento) {
		this.id = id;
		this.estaciones = estaciones;
		this.precipitaciones = precipitaciones;
		this.temperaturaC = temperaturaC;
		this.velocidadViento = velocidadViento;
	}

	public DatosId getId() {
		return this.id;
	}

	public void setId(DatosId id) {
		this.id = id;
	}

	public Estaciones getEstaciones() {
		return this.estaciones;
	}

	public void setEstaciones(Estaciones estaciones) {
		this.estaciones = estaciones;
	}

	public String getPrecipitaciones() {
		return this.precipitaciones;
	}

	public void setPrecipitaciones(String precipitaciones) {
		this.precipitaciones = precipitaciones;
	}

	public int getTemperaturaC() {
		return this.temperaturaC;
	}

	public void setTemperaturaC(int temperaturaC) {
		this.temperaturaC = temperaturaC;
	}

	public int getVelocidadViento() {
		return this.velocidadViento;
	}

	public void setVelocidadViento(int velocidadViento) {
		this.velocidadViento = velocidadViento;
	}

}
