package modelo;
// Generated 16 dic 2021 19:50:39 by Hibernate Tools 5.5.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Estaciones generated by hbm2java
 */
public class Estaciones implements java.io.Serializable {

	private int codEstacion;
	private Municipios municipios;
	private double coordenadaX;
	private double coordenadaY;
	private Set datoses = new HashSet(0);

	public Estaciones() {
	}

	public Estaciones(int codEstacion, Municipios municipios, double coordenadaX, double coordenadaY) {
		this.codEstacion = codEstacion;
		this.municipios = municipios;
		this.coordenadaX = coordenadaX;
		this.coordenadaY = coordenadaY;
	}

	public Estaciones(int codEstacion, Municipios municipios, double coordenadaX, double coordenadaY, Set datoses) {
		this.codEstacion = codEstacion;
		this.municipios = municipios;
		this.coordenadaX = coordenadaX;
		this.coordenadaY = coordenadaY;
		this.datoses = datoses;
	}

	public int getCodEstacion() {
		return this.codEstacion;
	}

	public void setCodEstacion(int codEstacion) {
		this.codEstacion = codEstacion;
	}

	public Municipios getMunicipios() {
		return this.municipios;
	}

	public void setMunicipios(Municipios municipios) {
		this.municipios = municipios;
	}

	public double getCoordenadaX() {
		return this.coordenadaX;
	}

	public void setCoordenadaX(double coordenadaX) {
		this.coordenadaX = coordenadaX;
	}

	public double getCoordenadaY() {
		return this.coordenadaY;
	}

	public void setCoordenadaY(double coordenadaY) {
		this.coordenadaY = coordenadaY;
	}

	public Set getDatoses() {
		return this.datoses;
	}

	public void setDatoses(Set datoses) {
		this.datoses = datoses;
	}

}
